name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .  # If Dockerfile is in the root, keep this as is
          file: ./path/to/Dockerfile  # Add this if Dockerfile is in a subdirectory
          push: true
          tags: |
            ashwani17/hello-ashwani-flask:${{ github.ref_name }}

      - name: Log out from Docker Hub
        run: docker logout
